const USERACTION = {
  UPDATE_CAPTION: "UPDATE_CAPTION",
  SELECT_NEW_IMAGE: "SELECT_NEW_IMAGE",
  PREVIEW_PANEL_DRAG: {
    START: "START",
    END: "END",
    DROP: "DROP"
  }
};

export { USERACTION };
